name: Deploy website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
  
      - name: install
        run: yarn
      
      # - name: build
      #   run: yarn build
      - name: build
        run: yarn build
  
      # - name: test
      #   run: yarn test --if-present
      
      - name: deploy with gh-pages to dev server
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     yarn deploy-dev -- -u "github-actions-bot <support+actions@github.com>"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # - name: deploy with gh-pages
      #   run: |
      #     git remote add website https://git:${GITHUB_TOKEN}@github.com/southwatervillagepreschool/southwatervillagepreschool.github.io.git
      #     yarn deploy-website -- -u "github-actions-bot <support+actions@github.com>"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
